nome = input('Digite seu nome:')
nome_espaco = '\t' + nome + ' ' + '\n' + ' '
print()
print(nome_espaco)
print()
print(nome_espaco.rstrip())
print()
print(nome_espaco.lstrip())
print()
print(nome_espaco.strip())
