nomes_amigos = ['luiz leal', 'luiz streamer brabo', 'sergio', 'ana', 'luane', 'gabi', 'giulia', 'guilherme pinheiro']

print(nomes_amigos[0].title())
print()
print(nomes_amigos[1].title())
print()
print(nomes_amigos[2].title())
print()
print(nomes_amigos[3].title())
print()
print(nomes_amigos[4].title())
print()
print(nomes_amigos[5].title())
print()
print(nomes_amigos[6].title())
print()